"""Auto-tuned block sizes for ragged paged attention v3.

The v3 kernel splits into three pallas_calls (DECODE / PREFILL / MIXED), each
with its own (bq_sz, bkv_sz, bq_csz, bkv_csz) 4-tuple. This table is keyed by
device + stage + the same workload signature used by v2.

Schema:
    TUNED_BLOCK_SIZES_V3[device_name][key] = (bq_sz, bkv_sz, bq_csz, bkv_csz)
    key = (stage, q_dtype, kv_dtype, q_heads, kv_heads, head_dim, page_size,
           max_num_tokens)
    stage in {"d", "p", "m"}

bq_sz / bkv_sz / bq_csz / bkv_csz are in tokens (not pages). Generated by
benchmark/kernels/flash_attention/get_block_spec_config_v3.py.
"""

import logging

from sgl_jax.srt.kernels.ragged_paged_attention.tuned_block_sizes import (
    get_simplified_key,
)
from sgl_jax.srt.kernels.ragged_paged_attention.util import get_tpu_version

logger = logging.getLogger(__name__)

# Track which (stage, key) combos we've already warned about, so each unique
# lookup miss prints at most once per process. Helps diagnose "tuned table
# was added but server still falls back to heuristic" bugs (usually a shape
# mismatch — e.g., wrong q_heads_per_shard).
_WARNED_MISSES: set[tuple] = set()


TUNED_BLOCK_SIZES_V3: dict[str, dict[tuple, tuple[int, int, int, int]]] = {
    "TPU v5": {},
    "TPU v6e": {},
    "TPU v7": {
        # MiMo-V2-Pro per-shard shape: q_heads=32 kv_heads=2 head_dim=192→256
        # page_size=256. Per-device shape derived from tp_size=32, dp_size=8
        # so attention TP = tp/dp = 4 → q=128/4=32, kv=8/4=2.
        # Tuned 2026-05-27 on tpuv7x-64-node, exp-2l37yy8ak4 with patched
        # kernel fd69b77c9 (unaliased m/l and bo/bq scratch to dodge XLA
        # MSA assertion).
        #
        # Decode (mnt = BSZ): heuristic bkv=1024 loses to bkv=2048 by
        # ~18-25% across BSZ {4..512}. BSZ {1,2} skipped (delta <10%).
        ("d", "bfloat16", "bfloat16", 32, 2, 256, 256, 4): (1, 2048, 1, 2048),
        ("d", "bfloat16", "bfloat16", 32, 2, 256, 256, 8): (1, 2048, 1, 2048),
        ("d", "bfloat16", "bfloat16", 32, 2, 256, 256, 16): (1, 2048, 1, 2048),
        ("d", "bfloat16", "bfloat16", 32, 2, 256, 256, 32): (1, 2048, 1, 2048),
        ("d", "bfloat16", "bfloat16", 32, 2, 256, 256, 64): (1, 2048, 1, 2048),
        ("d", "bfloat16", "bfloat16", 32, 2, 256, 256, 128): (1, 2048, 1, 2048),
        ("d", "bfloat16", "bfloat16", 32, 2, 256, 256, 256): (1, 2048, 1, 2048),
        ("d", "bfloat16", "bfloat16", 32, 2, 256, 256, 512): (1, 2048, 1, 2048),
        # Prefill at chunk_prefill_size=2048: heuristic bq=4 bkv=1024 loses
        # to bq=32 bkv=512 by +75%. Heuristic's bq=min(MAX_BQ=32, max_q//2)
        # gives bq=4 when max_q=8 (post page-alignment), 8× too small.
        ("p", "bfloat16", "bfloat16", 32, 2, 256, 256, 2048): (32, 512, 32, 512),
        # Mixed at mnt=2048: same +75% pattern as prefill (bq=4→32, bkv=1024
        # →512). Verified 2026-05-27 on exp-6h1zm7mqq6 (isolated m-stage).
        # The earlier silent-fail in exp-2l37yy8ak4 was JAX-state pollution
        # from p mnt=4096/8192's data-generator bug, not q=32 or the patch.
        ("m", "bfloat16", "bfloat16", 32, 2, 256, 256, 2048): (32, 512, 32, 512),
    },
}


def get_tuned_block_sizes_v3(
    stage: str,
    q_dtype,
    kv_dtype,
    actual_num_q_heads: int,
    actual_num_kv_heads: int,
    head_dim: int,
    page_size: int,
    max_num_tokens: int,
) -> tuple[int, int, int, int] | None:
    """Look up (bq_sz, bkv_sz, bq_csz, bkv_csz) from the v3 tuned table.

    Returns None if no entry matches; caller should fall back to the heuristic
    in ragged_paged_attention_v3.get_default_block_sizes.
    """
    if stage not in ("d", "p", "m"):
        raise ValueError(f"stage must be one of d/p/m, got {stage!r}")

    tpu_version = get_tpu_version()
    if tpu_version < 5:
        return None

    device_name, *signature = get_simplified_key(
        page_size,
        q_dtype,
        kv_dtype,
        actual_num_q_heads,
        actual_num_kv_heads,
        head_dim,
        max_num_tokens,
    )

    table = TUNED_BLOCK_SIZES_V3.get(device_name)
    if not table:
        return None

    key = (stage, *signature)
    hit = table.get(key)
    if hit is None and key not in _WARNED_MISSES:
        _WARNED_MISSES.add(key)
        logger.info(
            "RPA v3 tuned-block-size LOOKUP MISS device=%s key=%s "
            "(falling back to heuristic). Add this key to TUNED_BLOCK_SIZES_V3 "
            "to enable tuning for this shape.",
            device_name,
            key,
        )
    return hit
