"""Auto-tuned block sizes for ragged paged attention v3.

The v3 kernel splits into three pallas_calls (DECODE / PREFILL / MIXED), each
with its own (bq_sz, bkv_sz, bq_csz, bkv_csz) 4-tuple. This table is keyed by
device + stage + the same workload signature used by v2.

Schema:
    TUNED_BLOCK_SIZES_V3[device_name][key] = (bq_sz, bkv_sz, bq_csz, bkv_csz)
    key = (stage, q_dtype, kv_dtype, q_heads, kv_heads, head_dim, page_size,
           max_num_tokens)
    stage in {"d", "p", "m"}

bq_sz / bkv_sz / bq_csz / bkv_csz are in tokens (not pages). Generated by
benchmark/kernels/flash_attention/get_block_spec_config_v3.py.
"""

import logging

from sgl_jax.srt.kernels.ragged_paged_attention.tuned_block_sizes import (
    get_simplified_key,
)
from sgl_jax.srt.kernels.ragged_paged_attention.util import get_tpu_version

logger = logging.getLogger(__name__)


TUNED_BLOCK_SIZES_V3: dict[str, dict[tuple, tuple[int, int, int, int]]] = {
    "TPU v5": {},
    "TPU v6e": {},
    "TPU v7": {},
}


def get_tuned_block_sizes_v3(
    stage: str,
    q_dtype,
    kv_dtype,
    actual_num_q_heads: int,
    actual_num_kv_heads: int,
    head_dim: int,
    page_size: int,
    max_num_tokens: int,
) -> tuple[int, int, int, int] | None:
    """Look up (bq_sz, bkv_sz, bq_csz, bkv_csz) from the v3 tuned table.

    Returns None if no entry matches; caller should fall back to the heuristic
    in ragged_paged_attention_v3.get_default_block_sizes.
    """
    if stage not in ("d", "p", "m"):
        raise ValueError(f"stage must be one of d/p/m, got {stage!r}")

    tpu_version = get_tpu_version()
    if tpu_version < 5:
        return None

    device_name, *signature = get_simplified_key(
        page_size,
        q_dtype,
        kv_dtype,
        actual_num_q_heads,
        actual_num_kv_heads,
        head_dim,
        max_num_tokens,
    )

    table = TUNED_BLOCK_SIZES_V3.get(device_name)
    if not table:
        return None

    key = (stage, *signature)
    return table.get(key)
