resources:
    accelerators: tpu-v6e-4 #
    accelerator_args:
        tpu_vm: True
        runtime_version: v2-alpha-tpuv6e # optional
file_mounts:
    ~/.ssh/id_rsa: ~/.ssh/id_rsa
setup: |
    chmod 600 ~/.ssh/id_rsa
    rm ~/.ssh/config
    # GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:Furion-cn/sgl-jax.git
    # cd /home/gcpuser/sky_workdir/sgl-jax && uv pip install -e python/

# run: |
# SGL_JAX_USE_JIT=1 JAX_COMPILATION_CACHE_DIR=/tmp/jax_compilation_cache
# uv run python -u -m sgl_jax.launch_server --model-path Qwen/Qwen-7B --engine-
# type jax --trust-remote-code --skip-server-warmup --dist-init-addr=0.0.0.0:10011 --nnodes=1 --tp-size=4 --device=tpu --random-seed=3 --node-rank=0 --mem-fraction-static=0.1 --max-prefill-tokens=4096 --download-dir=/tmp/ --kv-cache-dtype=bf16