"""Auto-tuned block sizes for the MLA v2 Pallas kernel.

The MLA v2 kernel (`mla_ragged_paged_attention`) accepts three block-size slots
indexed `(decode, prefill, mixed)`, but the entry function dispatches the three
pallas_calls as `(BATCHED_DECODE, DECODE-tail, MIXED)`:

  - BATCHED_DECODE and DECODE-tail share slot[0]
  - slot[1] (PREFILL) is currently dead code (kernel.py TODO)
  - MIXED uses slot[2]

So the table only carries two `case_label` buckets:

  - "decode": one entry covers slot[0] AND `decode_batch_size`
  - "mixed":  one entry covers slot[2]

Schema:
    TUNED_BLOCK_SIZES_MLA[device_name][key] = config_tuple
    key = (case_label, q_dtype, kv_dtype, num_q_heads, kv_lora_rank,
           qk_rope_head_dim, page_size, max_num_tokens)
    case_label in {"decode", "mixed"}
    config_tuple ("decode") = (num_kv_pages_per_block, num_queries_per_block,
                               decode_batch_size)
    config_tuple ("mixed")  = (num_kv_pages_per_block, num_queries_per_block)

`num_q_heads`, `page_size`, `max_num_tokens` are normalized via `next_power_of_2`
to bucket nearby shapes. `kv_lora_rank` / `qk_rope_head_dim` are passed through
unchanged (they are model constants, not runtime-variable).

Generated by `benchmark/kernels/mla/get_block_spec_config_mla.py`.
"""

from __future__ import annotations

import logging

import jax.numpy as jnp

from sgl_jax.srt.kernels.ragged_paged_attention.util import (
    get_tpu_version,
    next_power_of_2,
)
from sgl_jax.srt.utils.jax_utils import get_device_name

logger = logging.getLogger(__name__)

# Track which (case, key) combos we've already warned about, so each unique
# lookup miss prints at most once per process. Helps diagnose "tuned table
# was added but server still falls back to default" bugs (usually a shape
# mismatch — wrong q_heads_per_shard, wrong page_size, or wrong mnt bucket).
_WARNED_MISSES: set[tuple] = set()

# Schema: see module docstring.
TUNED_BLOCK_SIZES_MLA: dict[str, dict[tuple, tuple]] = {
    "TPU v5": {},
    "TPU v6e": {},
    "TPU v7": {
        # ===== Ling-2.6-1T (kv_lora_rank=512, qk_rope_head_dim=64) =====
        # Production deploy: --tp-size 32 --dp-size 4 --page-size 256
        # → attention_tp = tp/dp = 8 → per-shard num_q_heads = 64/8 = 8.
        # Server-jit per-shard mnt buckets (= global / dp_size=4):
        #   decode bs_buckets = [64,128,256,512] → per-shard mnt {16,32,64,128}
        #   mixed token_buckets = [512,1024,2048,4096,8192]
        #     → per-shard mnt {128,256,512,1024,2048}
        # Steady-state hot for 16k input + chunked-prefill=2048:
        #   prefill chunk per-shard mnt = 2048/4 = 512 (mixed case)
        #   decode per-shard mnt depends on running req count (∈ above)
        #
        # Tuned 2026-05-29 on falcon exp-vj0fm1psbw (single v7x host, 8 cores)
        # against hardcoded heuristic decode=(3,1,4) / mixed=(1,16).
        # Tuner uses scope-name-matched extraction of pallas_call
        # device_duration_ps (matches the kernel's `MLA-bd-...` /
        # `MLA-m-...` named_scope) → pure kernel device time.
        # Cross-validated: production profiling shows decode dp=4 tp=8 with
        # 128-concurrency (per-DP 32) ≈ 350us; tuner heur (3,1,4) at
        # mnt=32 measured 347us — match.
        #
        # Wins (pure kernel device time):
        #   decode mnt=16:  +16.2%  (0.147ms vs 0.176ms)
        #   decode mnt=32:  +18.1%  (0.284ms vs 0.347ms)
        #   decode mnt=64:  +19.4%  (0.557ms vs 0.691ms)
        #   decode mnt=128: +20.0%  (1.104ms vs 1.380ms)
        #   mixed mnt=512:  +85.6%  (0.266ms vs 1.841ms)
        #   mixed mnt=1024: +86.2%  (0.546ms vs 3.966ms)
        #   mixed mnt=2048: +87.2%  (1.162ms vs 9.065ms)  ← user prefill chunk
        #   mixed mnt=4096: +88.4%  (2.616ms vs 22.638ms)
        #
        # See benchmark/kernels/mla/get_block_spec_config_mla.py.
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 256, 16): (16, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 256, 32): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 256, 64): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 256, 128): (32, 1, 2),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 256, 512): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 256, 1024): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 256, 2048): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 256, 4096): (8, 256),
    },
}


def get_tuned_block_sizes_mla(
    case_label: str,
    q_dtype,
    kv_dtype,
    actual_num_q_heads: int,
    kv_lora_rank: int,
    qk_rope_head_dim: int,
    page_size: int,
    max_num_tokens: int,
) -> tuple | None:
    """Look up the tuned block-size config from the MLA table.

    Args:
        case_label: "decode" or "mixed". The MLA kernel runs
            BATCHED_DECODE+DECODE-tail with a single config (slot[0]) and
            MIXED with another (slot[2]); slot[1] is dead. So callers query
            this function twice — once per case — and combine.
        q_dtype, kv_dtype: tensor dtypes (jax.numpy or numpy dtype).
        actual_num_q_heads: per-shard num q heads (post shard_map).
        kv_lora_rank: model constant; latent KV dim. Not normalized.
        qk_rope_head_dim: model constant; rope head dim. Not normalized.
        page_size: page size in tokens.
        max_num_tokens: padded total token count seen by the kernel
            (= `ql_nope.shape[0]`); already a server-precompiled bucket.

    Returns:
        - For case_label="decode": (num_kv_pages_per_block,
                                    num_queries_per_block,
                                    decode_batch_size) or None on miss.
        - For case_label="mixed":  (num_kv_pages_per_block,
                                    num_queries_per_block) or None on miss.
    """
    if case_label not in ("decode", "mixed"):
        raise ValueError(f"case_label must be 'decode' or 'mixed', got {case_label!r}")

    tpu_version = get_tpu_version()
    if tpu_version < 5:
        return None

    device_name = get_device_name()
    table = TUNED_BLOCK_SIZES_MLA.get(device_name)
    if table is None:
        # Device not supported at all (vs. supported-but-empty, which still
        # logs a miss so operators know to populate it).
        return None

    key = (
        case_label,
        jnp.dtype(q_dtype).name,
        jnp.dtype(kv_dtype).name,
        next_power_of_2(actual_num_q_heads),
        int(kv_lora_rank),
        int(qk_rope_head_dim),
        next_power_of_2(page_size),
        next_power_of_2(max_num_tokens),
    )

    hit = table.get(key)
    if hit is None and key not in _WARNED_MISSES:
        _WARNED_MISSES.add(key)
        logger.info(
            "MLA tuned-block-size LOOKUP MISS device=%s key=%s "
            "(falling back to hardcoded default). Add this key to "
            "TUNED_BLOCK_SIZES_MLA[%s] to enable tuning for this shape.",
            device_name,
            key,
            device_name,
        )
    return hit
