#!/usr/bin/env python3
"""Open/update GitHub issues + Slack from a trend drift report.

Consumes the drift.json from check_trend_threshold.py. Runs on a gh-capable
runner and reuses ci_common's shared issue helpers (same path as
ci_failure_issues.py), deduping per config by a hidden body marker. The
trend-alert label is a one-time repo setup that narrows the open-issue scan.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "utils"))
from ci_common import (  # noqa: E402
    add_issue_comment,
    create_issue,
    escape_mrkdwn,
    find_open_issue,
    sanitize_marker_value,
    utc_now,
)

ISSUE_MARKER_PREFIX = "trend-alert"
ISSUE_LABEL = "trend-alert"


def build_marker(config: str) -> str:
    """Hidden body marker used to find this config's existing issue."""
    return f"<!-- {ISSUE_MARKER_PREFIX}:config={sanitize_marker_value(config)} -->"


def load_drift(path: str) -> dict[str, list[dict[str, Any]]]:
    """Read drift.json -> {config: [...]}. Raises on missing/corrupt so the
    caller can tell a transport failure from a genuine no-drift report."""
    with open(path) as f:
        data = json.load(f)
    configs = data.get("configs")
    if not isinstance(configs, dict):
        raise ValueError("drift report has no 'configs' object")
    return configs


def _point_str(point: Any) -> str:
    if not point:
        return "-"
    c, i, o = point
    return f"c{c}-i{i}-o{o}"


def drift_table(items: list[dict[str, Any]]) -> str:
    """Render the shared drift-detail table used by both issue body and comment."""
    lines = [
        "| metric | point | recent | baseline | change | z (σ) | direction | points |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for it in items:
        # .get default can't catch present-but-None zscore (flat baseline)
        z = it.get("zscore")
        z = "-" if z is None else z
        lines.append(
            "| {metric} | {point} | {recent} | {baseline} | {pct:+.2f}% | {z} | {direction} | "
            "{nr}+{nb} |".format(
                metric=it["metric"],
                point=_point_str(it.get("point")),
                recent=it["recent_median"],
                baseline=it["baseline_median"],
                pct=it["pct_change"],
                z=z,
                direction=it["direction"],
                nr=it["n_recent"],
                nb=it["n_baseline"],
            )
        )
    return "\n".join(lines)


def issue_title(config: str, n: int) -> str:
    return f"[Trend Alert] {config}: {n} metric(s) drifting"


def issue_body(config: str, items: list[dict[str, Any]], marker: str, timestamp: str) -> str:
    return "\n".join(
        [
            marker,
            "## Trend Alert",
            "",
            f"Config `{config}` has {len(items)} metric(s) drifting beyond threshold "
            "(recent window vs baseline window, adverse direction only).",
            "",
            drift_table(items),
            "",
            f"_Updated at {timestamp}. Auto-generated by the nightly trend monitor._",
        ]
    )


def comment_body(config: str, items: list[dict[str, Any]], marker: str, timestamp: str) -> str:
    return "\n".join(
        [
            marker,
            "### Trend drift still present",
            "",
            drift_table(items),
            "",
            f"_Updated at {timestamp}._",
        ]
    )


def process_drifts(repo: str, configs: dict[str, list[dict[str, Any]]], *, dry_run: bool):
    """Open/update one issue per drifting config. Returns (records, issue_links)."""
    timestamp = utc_now()
    records = []
    issue_links: dict[str, str] = {}
    for config in sorted(configs):
        items = configs[config]
        marker = build_marker(config)
        try:
            if dry_run:
                records.append({"config": config, "action": "dry-run", "issue_url": ""})
                continue
            # Dedup scans only ISSUE_LABEL'd issues, so the label is a prerequisite:
            # strip it from a live alert and the next run opens a duplicate.
            existing = find_open_issue(repo, marker, labels=ISSUE_LABEL)
            if existing:
                add_issue_comment(
                    repo, int(existing["number"]), comment_body(config, items, marker, timestamp)
                )
                number, url, action = existing["number"], existing["url"], "updated"
            else:
                created = create_issue(
                    repo,
                    {
                        "title": issue_title(config, len(items)),
                        "body": issue_body(config, items, marker, timestamp),
                        "labels": [ISSUE_LABEL],
                    },
                )
                number, url, action = created["number"], created["url"], "created"
            issue_links[config] = url
            records.append(
                {"config": config, "issue_number": number, "issue_url": url, "action": action}
            )
        except Exception as exc:  # one config failing must not abort the rest
            records.append({"config": config, "action": "error", "error": str(exc)})
            print(f"Warning: failed to upsert issue for {config}: {exc}", file=sys.stderr)
    return records, issue_links


def format_slack(configs: dict[str, list[dict[str, Any]]], issue_links: dict[str, str]) -> str:
    """Slack mrkdwn summary, or '' when there is no drift."""
    if not configs:
        return ""
    lines = [
        f":chart_with_downwards_trend: *Nightly Trend Alert* — {len(configs)} config(s) drifting"
    ]
    for config in sorted(configs):
        url = issue_links.get(config)
        header = f"*{escape_mrkdwn(config)}*" + (f"  <{url}|issue>" if url else "")
        lines += ["", header]
        for it in configs[config]:
            lines.append(
                "• {metric} {pct:+.1f}% ({direction})".format(
                    metric=escape_mrkdwn(it["metric"]),
                    pct=it["pct_change"],
                    direction=it["direction"],
                )
            )
    text = "\n".join(lines)
    if len(text) > 2900:
        text = text[:2900].rsplit("\n", 1)[0] + "\n… (truncated)"
    return text


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Open/update issues + Slack from a drift report")
    parser.add_argument("--repo", required=True)
    parser.add_argument("--drift", required=True, help="drift.json from check_trend_threshold.py")
    parser.add_argument("--output", default="trend_alert_issues.json")
    parser.add_argument("--slack-output", default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    try:
        configs = load_drift(args.drift)
    except (OSError, ValueError) as exc:
        # Missing/corrupt report = monitor/artifact failed. Warn loudly rather
        # than silently act like "no drift" (which would hide a regression).
        print(
            f"::warning::Trend drift report at {args.drift} is unusable ({exc}); "
            "the monitor job or its artifact upload likely failed — no alert was run.",
            file=sys.stderr,
        )
        return 0

    records, issue_links = process_drifts(args.repo, configs, dry_run=args.dry_run)

    with open(args.output, "w") as f:
        json.dump(
            {"schema_version": 1, "updated_at": utc_now(), "drifting_configs": records},
            f,
            indent=2,
            sort_keys=True,
        )

    if args.slack_output is not None:
        try:
            slack = format_slack(configs, issue_links)
        except Exception as exc:  # a malformed detail must not crash the whole step
            print(
                f"::warning::failed to format Slack summary ({exc}); skipping Slack",
                file=sys.stderr,
            )
            slack = ""
        with open(args.slack_output, "w") as f:
            f.write(slack)

    print(f"Processed {len(configs)} drifting config(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
