model_arch: black-forest-labs/FLUX.1-dev
# how can we mapping model name to stage config yaml and impl class
stage_args:
 - stage_id: 0
   stage_sub_dir: text_encoder,text_encoder_2
   runtime:
     num_tpus: 1
     max_batch_size: 1
   scheduler: text_encoder
   final_output: false
   scheduler_params: {"tokenizers": "tokenizer,tokenizer_2"}
   model_class: CLIPTextModel,T5EncoderModel


 - stage_id: 1
   stage_sub_dir: transformer
   runtime:
     num_tpus: 1
     device_kind: cpu
     max_batch_size: 1
   scheduler: diffusion
   scheduler_params: {Scheduler: FlowMatchEulerDiscreteScheduler}
   model_class: FluxTransformer2DModel
   final_output: false

 - stage_id: 2
   stage_sub_dir: vae
   runtime:
     num_tpus: 1
     device_kind: cpu
     max_batch_size: 1
   scheduler: vae
   scheduler_params: {}
   model_class: AutoencoderKL
   final_output: true
