---
apiVersion: v1
kind: Service
metadata:
  name: niu-mimo-v64-headless-svc
spec:
  clusterIP: None
  selector:
    job-name: niu-mimo-v64
  ports:
  - name: dist-init
    port: 5000
  - name: tpu-process
    port: 8471
  - name: http
    port: 30271
---
apiVersion: batch/v1
kind: Job
metadata:
  name: niu-mimo-v64
spec:
  backoffLimit: 6
  completionMode: Indexed
  parallelism: 16
  completions: 16
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      subdomain: niu-mimo-v64-headless-svc
      restartPolicy: Never
      serviceAccountName: gcs-account
      nodeSelector:
        cloud.google.com/gke-nodepool: ramezes-v6e-64
        cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
        cloud.google.com/gke-tpu-topology: 8x8
      containers:
      - name: jax-tpu
        image: us-docker.pkg.dev/cloud-tpu-images/jax-ai-image/tpu:jax0.8.1-rev1
        command: ["bash", "-lc"]
        args:
        - sleep infinity
        env:
        - name: HF_HUB_DOWNLOAD_TIMEOUT
          value: "300"
        - name: JAX_COMPILATION_CACHE_DIR
          value: /workdir/jax_cache
        - name: TPU_WORKER_HOSTNAMES
          value: niu-mimo-v64-0.niu-mimo-v64-headless-svc,niu-mimo-v64-1.niu-mimo-v64-headless-svc,niu-mimo-v64-2.niu-mimo-v64-headless-svc,niu-mimo-v64-3.niu-mimo-v64-headless-svc,niu-mimo-v64-4.niu-mimo-v64-headless-svc,niu-mimo-v64-5.niu-mimo-v64-headless-svc,niu-mimo-v64-6.niu-mimo-v64-headless-svc,niu-mimo-v64-7.niu-mimo-v64-headless-svc,niu-mimo-v64-8.niu-mimo-v64-headless-svc,niu-mimo-v64-9.niu-mimo-v64-headless-svc,niu-mimo-v64-10.niu-mimo-v64-headless-svc,niu-mimo-v64-11.niu-mimo-v64-headless-svc,niu-mimo-v64-12.niu-mimo-v64-headless-svc,niu-mimo-v64-13.niu-mimo-v64-headless-svc,niu-mimo-v64-14.niu-mimo-v64-headless-svc,niu-mimo-v64-15.niu-mimo-v64-headless-svc
        - name: TPU_WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['batch.kubernetes.io/job-completion-index']
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['batch.kubernetes.io/job-completion-index']
        ports:
        - containerPort: 30271
          name: http
        - containerPort: 5000
          name: dist-init
        resources:
          requests:
            ephemeral-storage: 35Gi
            google.com/tpu: "4"
          limits:
            ephemeral-storage: 70Gi
            google.com/tpu: "4"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /models
          name: gcs-fuse-csi-ephemeral
        - mountPath: /workdir
          name: workdir
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 32Gi
      - name: gke-gcsfuse-tmp
        emptyDir: {}
      - name: gke-gcsfuse-buffer
        emptyDir: {}
      - name: gke-gcsfuse-cache
        emptyDir:
          medium: Memory
      - name: gcs-fuse-csi-ephemeral
        persistentVolumeClaim:
          claimName: inference-model-storage-poc-tpu-hns-pvc
      - name: workdir
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 200Gi
              storageClassName: dynamic-rwo
