apiVersion: v1
kind: PersistentVolume
metadata:
  name: moe-bench-gcs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: moe-bench-gcs-sc
  mountOptions:
    - implicit-dirs
    - metadata-cache:ttl-secs:5
    - metadata-cache:stat-cache-max-size-mb:64
    - metadata-cache:type-cache-max-size-mb:8
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: inference-model-storage-poc-tpu
  claimRef:
    name: moe-bench-gcs-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moe-bench-gcs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: moe-bench-gcs-sc
