"""EAGLE speculative-decoding state objects and their batch transitions."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, ClassVar

import jax
import numpy as np
from jax.sharding import NamedSharding
from jax.sharding import PartitionSpec as P
from jax.tree_util import register_pytree_node_class

from sgl_jax.srt.managers.schedule_batch import (
    ModelWorkerBatch,
    ScheduleBatch,
    get_last_loc,
)
from sgl_jax.srt.mem_cache.common import (
    alloc_paged_token_slots_extend,
    alloc_token_slots,
)
from sgl_jax.srt.model_executor.forward_batch_info import CaptureHiddenMode, ForwardMode
from sgl_jax.srt.speculative.overlap_utils import uses_host_eagle_state
from sgl_jax.srt.speculative.spec_info import assign_req_to_token_pool

if TYPE_CHECKING:
    from sgl_jax.srt.managers.scheduler import GenerationBatchResult


def _is_jax_leaf(value: Any) -> bool:
    """Detect sentinel nodes generated by jax.tree_util when shaping pytrees."""
    cls = value.__class__
    return cls.__name__ == "Leaf" and cls.__module__.startswith("jax.")


def _as_int32_array(value: Any, *, fallback: int = -1) -> Any:
    """Convert scalar-like metadata into int32 arrays without forcing device work."""
    if value is None:
        return None
    if isinstance(value, jax.Array):
        return value
    if isinstance(value, np.ndarray):
        return np.asarray(value, dtype=np.int32)
    if isinstance(value, (int, np.integer)):
        return np.asarray(int(value), dtype=np.int32)
    if isinstance(value, (list, tuple)):
        return np.asarray(value, dtype=np.int32)
    if _is_jax_leaf(value):
        return np.asarray(fallback, dtype=np.int32)
    try:
        return np.asarray(value, dtype=np.int32)
    except (TypeError, ValueError) as exc:
        raise TypeError(
            f"Unable to convert value of type {type(value)} into int32 metadata array."
        ) from exc


@register_pytree_node_class
@dataclass
class EagleDraftInput:
    """Next-round draft state — the only persistent cross-round spec state.

    MUST NOT hold worker/runner/pool/future handles.
    Under DP (Route 1), per-request fields use DP-padded order.
    """

    ALLOC_LEN_PER_DECODE: ClassVar[int] = None

    # --- Cross-round draft state (device arrays, consumed by next draft) ---
    #: device ``(b, width)`` — raw draft-vocabulary token ids. Width is one
    #: after prefill and ``num_steps`` after recurrent expansion.
    topk_index: jax.Array | None = None
    #: device ``(b, hidden_size)`` — minimal hidden state for the next fused
    #: EAGLE/EAGLE3 draft-extend.
    hidden_states: jax.Array | None = None
    #: static metadata (pytree aux); changing it triggers a new compile shape.
    capture_hidden_mode: CaptureHiddenMode = CaptureHiddenMode.FULL

    # --- Draft-extend inputs (device unless ``_cpu`` suffixed) ---
    #: device ``(b,)`` — verified token starting the next draft.
    verified_id: jax.Array | None = None
    #: device ``(b,)`` — accepted length used to select hidden in draft-extend.
    accept_length: jax.Array | None = None
    #: host ``(b,)`` int32 mirror of ``accept_length`` for scheduler bookkeeping.
    accept_length_cpu: np.ndarray | None = None

    # --- Attention-backend metadata (host, participates in metadata build) ---
    kv_indices: np.ndarray | None = None

    # --- Padding shape (static; participates in JIT cache key) ---
    num_tokens_per_batch: int = -1
    num_tokens_for_logprob_per_batch: int = -1

    # --- KV lifetime (host, scheduler-visible) ---
    #: host ``(b,)`` — KV length already allocated in ``req_to_token_pool`` for
    #: next-round pre-allocation and over-allocated slot release. Distinct from
    #: ``accept_length`` (logical) and ``new_seq_lens`` (scheduler-visible).
    allocate_lens: np.ndarray | None = None
    #: host ``(b,)`` — scheduler-visible logical length after verify. May be
    #: derived from ``old_seq_lens + accept_length`` if not stored.
    new_seq_lens: np.ndarray | None = None
    #: host ``(b,)`` — req_pool_indices used to gather relay-buffer state.
    future_indices: np.ndarray | None = None

    def new_tokens_required_next_decode(self, requests, page_size: int) -> int:
        target_alloc = self.ALLOC_LEN_PER_DECODE * 2
        total = 0
        for req in requests:
            cur = req.kv_allocated_len
            nxt = max(cur, req.kv_committed_len + target_alloc)
            total += ((nxt + page_size - 1) // page_size) * page_size - (
                (cur + page_size - 1) // page_size
            ) * page_size
        return total

    def tree_flatten(self):
        accept_length_cpu_arr = (
            np.empty((0,), dtype=np.int32)
            if self.accept_length_cpu is None
            else _as_int32_array(self.accept_length_cpu, fallback=0)
        )

        num_tokens_per_batch_arr = _as_int32_array(self.num_tokens_per_batch)
        num_tokens_for_logprob_arr = _as_int32_array(self.num_tokens_for_logprob_per_batch)

        children = (
            self.topk_index,
            self.hidden_states,
            self.verified_id,
            self.accept_length,
            self.kv_indices,
            self.future_indices,
            accept_length_cpu_arr,
            num_tokens_per_batch_arr,
            num_tokens_for_logprob_arr,
        )

        aux_data = {
            "capture_hidden_mode": self.capture_hidden_mode,
        }
        return (children, aux_data)

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        obj = cls.__new__(cls)
        obj.capture_hidden_mode = aux_data["capture_hidden_mode"]
        obj.topk_index = children[0]
        obj.hidden_states = children[1]
        obj.verified_id = children[2]
        obj.accept_length = children[3]
        obj.kv_indices = children[4]
        obj.future_indices = children[5]

        obj.accept_length_cpu = children[6]
        obj.num_tokens_per_batch = children[7]
        obj.num_tokens_for_logprob_per_batch = children[8]

        return obj

    def prepare_for_extend_after_target_prefill(self, model_worker_batch: ModelWorkerBatch):
        # Prefill only generate 1 token.
        assert self.verified_id.shape[0] == model_worker_batch.real_bs, (
            f"{self.verified_id.shape=} {model_worker_batch.real_bs=}"
        )

        # Walk the DP-padded layout in (rank, slot) order so token offsets line
        # up with mwb.input_ids' token-major DP layout. Iterating real_bs and
        # indexing extend_seq_lens by `i` skipped real reqs whose padded slot
        # index > i (e.g. dp>1 prefill with only rank>0 active).
        dp_size = model_worker_batch.dp_size
        # per_dp_bs_size already covers both dp=1 (= total_bs) and dp>1
        # (= total_bs / dp). Hardcoding 1 here drops dp=1 multi-req.
        per_dp_bs = model_worker_batch.per_dp_bs_size
        total_tok = len(model_worker_batch.input_ids)
        per_dp_tok = total_tok // dp_size
        extend_seq_lens = model_worker_batch.extend_seq_lens
        flat_idx = 0  # index into self.verified_id (cross-rank flat)
        for dp_rank in range(dp_size):
            pt = dp_rank * per_dp_tok
            for slot_in_rank in range(per_dp_bs):
                slot = dp_rank * per_dp_bs + slot_in_rank
                extend_len = int(extend_seq_lens[slot])
                if extend_len == 0:
                    continue
                input_ids = model_worker_batch.input_ids[pt : pt + extend_len]
                model_worker_batch.input_ids[pt : pt + extend_len] = np.concatenate(
                    (input_ids[1:], self.verified_id[flat_idx].reshape(1))
                )
                pt += extend_len
                flat_idx += 1
        assert flat_idx == model_worker_batch.real_bs, (
            f"prepare_for_extend_after_target_prefill mismatch: walked {flat_idx} "
            f"real reqs but real_bs={model_worker_batch.real_bs}"
        )

    def prepare_for_extend_after_verify(
        self,
        model_worker_batch: ModelWorkerBatch,
        draft_model_runner: Any,
        batch_output: GenerationBatchResult,
        speculative_num_draft_tokens: int,
    ):
        uses_host_state = (
            model_worker_batch.spec_algorithm is not None
            and model_worker_batch.spec_algorithm.is_eagle()
            and getattr(batch_output.next_draft_input, "future_indices", None) is None
        )
        model_worker_batch.spec_info_padded = self
        sel = model_worker_batch.logits_indices_selector
        model_worker_batch.seq_lens[sel] = (
            model_worker_batch.seq_lens[sel] + speculative_num_draft_tokens - 1
        )
        bs = batch_output.accept_lens.shape[0]
        step_plus_1 = model_worker_batch.input_ids.shape[0] // bs
        positions = getattr(batch_output.next_draft_input, "positions", None)
        if positions is not None and not uses_host_state:
            model_worker_batch.positions = positions
        model_worker_batch.extend_seq_lens = np.zeros((bs,), dtype=np.int32)
        model_worker_batch.extend_seq_lens[sel] = step_plus_1
        # Per-rank-local cumsum: _select_hidden_states is a shard_map rank-local
        # gather, so indices must be offsets into each rank's own hidden shard.
        dp = model_worker_batch.dp_size
        per_dp = model_worker_batch.per_dp_bs_size if dp > 1 else bs
        model_worker_batch.logits_indices = (
            model_worker_batch.extend_seq_lens.reshape(dp, per_dp)
            .cumsum(axis=1, dtype=np.int32)
            .ravel()
            - 1
        )
        model_worker_batch.capture_hidden_mode = CaptureHiddenMode.FULL
        model_worker_batch.spec_info_padded.capture_hidden_mode = CaptureHiddenMode.FULL
        model_worker_batch.forward_mode = ForwardMode.DRAFT_EXTEND
        model_worker_batch.spec_info_padded.hidden_states = (
            batch_output.next_draft_input.hidden_states
        )
        if model_worker_batch.spec_info_padded.accept_length is None:
            model_worker_batch.spec_info_padded.accept_length = batch_output.accept_lens
        model_worker_batch.input_ids = batch_output.next_draft_input.verified_id
        forward_metadata = draft_model_runner.attn_backend.prepare_paged_kv_layout(
            model_worker_batch
        )

        draft_model_runner.attn_backend.forward_metadata = forward_metadata
        from sgl_jax.srt.layers.logits_processor import LogitsMetadata
        from sgl_jax.srt.utils.jax_utils import device_array

        if model_worker_batch.return_logprob:
            logits_metadata = LogitsMetadata.from_model_worker_batch(
                model_worker_batch, draft_model_runner.mesh
            )
        else:
            sharding = NamedSharding(draft_model_runner.mesh, P("data"))

            def _to_device(value):
                if value is None:
                    return None
                if isinstance(value, jax.Array):
                    current_sharding = value.sharding
                    if current_sharding == sharding:
                        return value
                    return jax.device_put(value, sharding)
                return device_array(value, sharding=sharding)

            extend_seq_lens_for_logits = getattr(
                model_worker_batch.spec_info_padded,
                "extend_seq_lens_for_draft_extend",
                None,
            )
            if extend_seq_lens_for_logits is None:
                extend_seq_lens_for_logits = model_worker_batch.extend_seq_lens
            logits_indices_for_logits = getattr(
                model_worker_batch.spec_info_padded,
                "logits_indices_for_draft_extend",
                None,
            )
            if logits_indices_for_logits is None:
                logits_indices_for_logits = model_worker_batch.logits_indices

            logits_metadata = LogitsMetadata(
                forward_mode=model_worker_batch.forward_mode,
                capture_hidden_mode=model_worker_batch.capture_hidden_mode,
                extend_return_logprob=False,
                extend_return_top_logprob=False,
                extend_token_ids_logprob=False,
                extend_seq_lens=_to_device(extend_seq_lens_for_logits),
                logits_indices=_to_device(logits_indices_for_logits),
                accept_lens=_to_device(model_worker_batch.spec_info_padded.accept_length),
                extend_seq_lens_cpu=None,
                extend_logprob_start_lens_cpu=None,
                extend_logprob_pruned_lens_cpu=None,
                top_logprobs_nums=model_worker_batch.top_logprobs_nums,
                token_ids_logprobs=model_worker_batch.token_ids_logprobs,
                extend_input_logprob_token_ids_device=_to_device(
                    model_worker_batch.extend_input_logprob_token_ids
                ),
            )
        return model_worker_batch, logits_metadata

    def prepare_for_decode(self, schedule_batch: ScheduleBatch):
        # spec_info / allocate_lens are global (flat across DP ranks). Allocate
        # per-rank (allocator + swa_mapping are per-dp_rank at dp>1); concat
        # back to global-flat. (#1053 P1-5b — was dp_rank=0 for all, so rank>0
        # reqs allocated from rank 0's pool / updated swa_mapping[0].)
        bs = schedule_batch.batch_size()
        assert self.allocate_lens.shape[0] == bs, (
            f" {self.allocate_lens.shape[0]=} but batch_size is {bs} "
        )
        page_size = schedule_batch.token_to_kv_pool_allocator.page_size
        new_alloc_chunks = []
        flat_off = 0
        uses_host_state = uses_host_eagle_state(
            schedule_batch.enable_overlap, schedule_batch.spec_algorithm
        )
        for dp_rank, info in enumerate(schedule_batch.reqs_info):
            if info.seq_lens is None or len(info.seq_lens) == 0:
                continue
            bs_r = len(info.seq_lens)
            if uses_host_state:
                seq_r = np.asarray(info.seq_lens)
                new_r = seq_r + self.ALLOC_LEN_PER_DECODE - 1
                old_r = self.allocate_lens[flat_off : flat_off + bs_r]
            else:
                old_r = np.asarray([req.kv_allocated_len for req in info.reqs], dtype=np.int32)
                committed_r = np.asarray(
                    [req.kv_committed_len for req in info.reqs], dtype=np.int32
                )
                new_r = np.maximum(old_r, committed_r + 2 * self.ALLOC_LEN_PER_DECODE)
            ext_r = int((new_r - old_r).sum())
            if page_size == 1:
                ocl_r = alloc_token_slots(schedule_batch.tree_cache, ext_r, dp_rank=dp_rank)
            else:
                last_loc_r = get_last_loc(
                    schedule_batch.req_to_token_pool.req_to_token,
                    info.req_pool_indices,
                    old_r,
                )
                ocl_r = alloc_paged_token_slots_extend(
                    schedule_batch.tree_cache,
                    old_r,
                    new_r,
                    last_loc_r,
                    ext_r,
                    dp_rank=dp_rank,
                )
            assign_req_to_token_pool(
                info.req_pool_indices, schedule_batch.req_to_token_pool, old_r, new_r, ocl_r
            )
            new_alloc_chunks.append(new_r)
            # Per-rank store (matches nospec extend); _get_spec_decode_mwb_dp
            # DP-segments these so each rank's P("data") shard = its own slots.
            info.out_cache_loc = np.asarray(ocl_r, dtype=np.int32)
            for req, allocated_len in zip(info.reqs, new_r):
                req.decode_batch_idx += 1
                req.kv_allocated_len = int(allocated_len)
                if not uses_host_state:
                    req.kv_committed_len += 1
            flat_off += bs_r
            info.seq_lens_sum = np.sum(info.seq_lens).item()

        self.allocate_lens = np.concatenate(new_alloc_chunks)

    def prepare_for_draft_decode(self, model_worker_batch: ModelWorkerBatch):
        self.capture_hidden_mode = CaptureHiddenMode.LAST
        self.num_tokens_per_batch = 1
        self.num_tokens_for_logprob_per_batch = 1
        model_worker_batch.return_hidden_states = False
        model_worker_batch.seq_lens_sum = np.sum(model_worker_batch.seq_lens)

    def _ensure_host(self):
        """Move device arrays to host (numpy) to avoid variable-shape device ops.

        Spec decode postprocessing (filter_batch, merge_batch, split/concat)
        operates on per-request arrays whose size varies with real_bs. Keeping
        these as jax.Array triggers implicit JIT compilation for each new shape.
        Converting to numpy first and re-uploading at bucket-padded size in
        _scatter_spec_info_to_dp_slots eliminates those persistent cache misses.
        """
        device_fields = ("topk_index", "hidden_states", "verified_id", "accept_length")
        to_copy = []
        for f in device_fields:
            v = getattr(self, f, None)
            if v is not None and hasattr(v, "copy_to_host_async"):
                jax.copy_to_host_async(v)
                to_copy.append(f)
        for f in to_copy:
            setattr(self, f, np.asarray(getattr(self, f)))

    def filter_batch(self, new_indices: np.ndarray, has_been_filtered: bool = True):
        new_indices = np.asarray(new_indices)
        if self.future_indices is not None:
            src = np.asarray(self.future_indices)
            idx = (
                slice(0, len(new_indices))
                if has_been_filtered and len(new_indices) == len(src)
                else new_indices
            )
            self.future_indices = src[idx]
            if self.allocate_lens is not None:
                self.allocate_lens = np.asarray(self.allocate_lens)[idx]
            if self.new_seq_lens is not None:
                self.new_seq_lens = np.asarray(self.new_seq_lens)[idx]
            if self.accept_length_cpu is not None:
                self.accept_length_cpu = np.asarray(self.accept_length_cpu)[idx]
            return

        self._ensure_host()
        if has_been_filtered and len(new_indices) == len(self.topk_index):
            self.topk_index = self.topk_index[: len(new_indices)]
            self.hidden_states = self.hidden_states[: len(new_indices)]
            self.verified_id = self.verified_id[: len(new_indices)]
            if self.allocate_lens is not None:
                self.allocate_lens = np.asarray(self.allocate_lens)[: len(new_indices)]
            if self.new_seq_lens is not None:
                self.new_seq_lens = np.asarray(self.new_seq_lens)[: len(new_indices)]
        else:
            self.topk_index = self.topk_index[new_indices]
            self.hidden_states = self.hidden_states[new_indices]
            self.verified_id = self.verified_id[new_indices]
            if self.allocate_lens is not None:
                self.allocate_lens = np.asarray(self.allocate_lens)[new_indices]
            if self.new_seq_lens is not None:
                self.new_seq_lens = np.asarray(self.new_seq_lens)[new_indices]

    def trim_to_length(self, n: int):
        self._ensure_host()
        for f in (
            "topk_index",
            "hidden_states",
            "verified_id",
            "allocate_lens",
            "new_seq_lens",
            "accept_length",
            "accept_length_cpu",
            "future_indices",
        ):
            v = getattr(self, f, None)
            if v is not None and len(v) != n:
                setattr(self, f, np.asarray(v)[:n])

    def merge_batch(self, spec_info: EagleDraftInput):
        if self.future_indices is not None or spec_info.future_indices is not None:
            assert self.future_indices is not None and spec_info.future_indices is not None, (
                "merge_batch requires both EagleDraftInput objects to carry future_indices "
                "on the relay-buffer path"
            )
            self.future_indices = np.concatenate(
                [np.asarray(self.future_indices), np.asarray(spec_info.future_indices)],
                axis=0,
            )
            if self.allocate_lens is not None and spec_info.allocate_lens is not None:
                self.allocate_lens = np.concatenate(
                    [np.asarray(self.allocate_lens), np.asarray(spec_info.allocate_lens)],
                    axis=0,
                )
            else:
                self.allocate_lens = None
            if self.new_seq_lens is not None and spec_info.new_seq_lens is not None:
                self.new_seq_lens = np.concatenate(
                    [np.asarray(self.new_seq_lens), np.asarray(spec_info.new_seq_lens)],
                    axis=0,
                )
            else:
                self.new_seq_lens = None
            if self.accept_length_cpu is not None and spec_info.accept_length_cpu is not None:
                self.accept_length_cpu = np.concatenate(
                    [np.asarray(self.accept_length_cpu), np.asarray(spec_info.accept_length_cpu)],
                    axis=0,
                )
            else:
                self.accept_length_cpu = None
            return

        if self.hidden_states is None:
            self.hidden_states = spec_info.hidden_states
            self.verified_id = spec_info.verified_id
            self.topk_index = spec_info.topk_index
            self.allocate_lens = spec_info.allocate_lens
            self.new_seq_lens = spec_info.new_seq_lens
            return
        if spec_info.hidden_states is None:
            return
        self._ensure_host()
        spec_info._ensure_host()
        self.hidden_states = np.concatenate([self.hidden_states, spec_info.hidden_states], axis=0)
        self.verified_id = np.concatenate([self.verified_id, spec_info.verified_id], axis=0)
        self_topk_index = np.asarray(self.topk_index)
        other_topk_index = np.asarray(spec_info.topk_index)
        if self_topk_index.shape[1] != other_topk_index.shape[1]:
            widths = {self_topk_index.shape[1], other_topk_index.shape[1]}
            if 1 not in widths:
                raise ValueError(
                    "Cannot merge EAGLE draft states with incompatible widths: "
                    f"{self_topk_index.shape[1]} and {other_topk_index.shape[1]}"
                )
            # A newly prefetched EAGLE/EAGLE3 request carries only its first draft
            # seed, while steady-state fused requests carry the full recurrent
            # chain. Downgrade the mixed batch to the common seed so one
            # bootstrap draft pass can rebuild every row consistently.
            self_topk_index = self_topk_index[:, :1]
            other_topk_index = other_topk_index[:, :1]
        self.topk_index = np.concatenate([self_topk_index, other_topk_index])
        self.allocate_lens = np.concatenate([self.allocate_lens, spec_info.allocate_lens])
        if self.new_seq_lens is not None and spec_info.new_seq_lens is not None:
            self.new_seq_lens = np.concatenate(
                [np.asarray(self.new_seq_lens), np.asarray(spec_info.new_seq_lens)]
            )
        else:
            self.new_seq_lens = None


@register_pytree_node_class
@dataclass
class EagleVerifyInput:
    """Minimal transient input for fused topk=1 target verification."""

    # --- Device arrays (enter target verify forward / sampling) ---
    #: device ``(b*draft_token_num,)`` — flattened draft tokens to verify.
    draft_token: jax.Array
    #: device ``(b*draft_token_num,)`` — verify positions (follows
    #: ``ForwardBatch`` host/device convention).
    positions: jax.Array

    def tree_flatten(self):
        children = (
            self.draft_token,
            self.positions,
        )
        return (children, None)

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        obj = cls.__new__(cls)
        obj.draft_token = children[0]
        obj.positions = children[1]

        return obj

    def prepare_for_verify(self, model_worker_batch: ModelWorkerBatch):
        sel = model_worker_batch.logits_indices_selector
        model_worker_batch.seq_lens[sel] = model_worker_batch.seq_lens[sel] - 1
        model_worker_batch.input_ids = self.draft_token
        model_worker_batch.positions = self.positions
        model_worker_batch.return_hidden_states = False
        model_worker_batch.forward_mode = ForwardMode.TARGET_VERIFY
        model_worker_batch.spec_info_padded = self
        model_worker_batch.capture_hidden_mode = CaptureHiddenMode.FULL
        model_worker_batch.extend_seq_lens = None
