#!/bin/bash
# sglang-jax MoE backend benchmark — 一键部署 v1/v2/v4 三方跑分
#
# 解决的问题：历史上有 3 个近乎一样的 YAML 文件互相手工派生，每次改
# 一个路径/依赖都要同步 3 份，经常遗漏导致部署失败。
#
# 用法（新 session 第一次用）：
#   1. cd /Users/wenqiao/gcp/sglang-jax
#   2. ./ling-test/deploy.sh --dry-run           # 只验证不部署
#   3. ./ling-test/longctx-bench/run.sh          # 一键部署全部 3 个
#      ./ling-test/longctx-bench/run.sh v1       # 只跑 v1
#      ./ling-test/longctx-bench/run.sh v1 v2    # 只跑 v1 和 v2
#
# 前置条件：
#   - kubectl 可用，TPU 节点池 tpu-v7-4-b / tpu-v7-4-c 就绪
#   - GCS tarball (sglang-jax-v4.tar.gz) 已是最新
#   - GCS bench 脚本 (ling_v3_flash_longctx_bench.py) 已是最新
#
# 生成时间：2026-06-24
# 模型：ling_v3_flash, bs=1, in=4096, out=2048, tp=4

set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

# ── Backend 定义（单一真相源）─────────────────────────────────────
# 每个 backend 的元组：label|moe_backend|nodepool|extra_packages|bs_paddings
#
# 格式：每行 5 个字段，| 分隔
#   label         - 短名，用于 job name 和日志
#   moe_backend   - MoEBackend 枚举值
#   nodepool      - GKE node pool
#   extra_packages - 额外 pip 包（空格分隔，无则为 -）
#   bs_paddings   - precompile_bs_paddings（无则为 -）

BACKENDS=(
  "v1|fused|tpu-v7-4-c|-|-"
  "v2|fused_v2|tpu-v7-4-b|einops fla-core triton|8"
  "v4|fused_v4|tpu-v7-4-a|-|-"
)

# ── 公共配置 ──────────────────────────────────────────────────────
IMAGE="python:3.12-slim"
TARBALL_URL="https://storage.googleapis.com/ainfer-tpu-bench-code/sglang-jax-v4.tar.gz"
BENCH_URL="https://storage.googleapis.com/ainfer-tpu-bench-code/ling_v3_flash_longctx_bench.py"
WEIGHTS_BUCKET="ant_asystem"
WEIGHTS_SUBDIR="models/ling_v3_flash"
MODEL_DIR="/tmp/models/ling_v3_flash"
GCS_WEIGHTS_PREFIX="gs://ant_asystem/models/ling_v3_flash"
COMPILE_CACHE_BASE="gs://ant_asystem/compile_cache/ling_v3_flash_longctx"
MOE_PARALLEL_GROUPS="8"
SGLANG_MOE_LOAD_WORKERS="32"
TP_SIZE="4"
TARGET_IN="4096"
TARGET_OUT="2048"
WARMUP_ROUNDS="1"
TIMED_ROUNDS="3"

# ── 生成单个 YAML ────────────────────────────────────────────────
gen_yaml() {
  local label="$1" moe_backend="$2" nodepool="$3" extra_pkgs="$4" bs_paddings="$5"

  local job_name="ling-v3-flash-longctx-bench-${label}"
  local compile_cache="${COMPILE_CACHE_BASE}_${label}"

  # 额外 pip install 行
  local extra_pip=""
  [ "$extra_pkgs" != "-" ] && extra_pip="pipi ${extra_pkgs}"

  # BS_PADDINGS env 行
  local bs_env=""
  [ "$bs_paddings" != "-" ] && bs_env="        - {name: BS_PADDINGS, value: \"${bs_paddings}\"}"

  cat <<YAML
# Auto-generated by longctx-bench/run.sh — DO NOT EDIT BY HAND
# Backend: ${label} (moe_backend=${moe_backend})
apiVersion: batch/v1
kind: Job
metadata:
  name: ${job_name}
  namespace: default
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: bench
        image: ${IMAGE}
        command: ["/bin/bash","-c"]
        args:
        - |
          set -e
          export PIP_DEFAULT_TIMEOUT=120; export PIP_RETRIES=10
          pipi() { for n in 1 2 3 4 5; do pip install -q "\$@" && return 0; echo "pip retry \$n"; sleep 5; done; return 1; }

          # ── System deps ──
          apt-get update -qq
          apt-get install -y -qq git curl gnupg lsb-release fuse >/dev/null
          rm -rf /var/lib/apt/lists/*

          # ── gcsfuse ──
          export GCSFUSE_REPO=gcsfuse-\$(lsb_release -c -s)
          echo "deb https://packages.cloud.google.com/apt \$GCSFUSE_REPO main" > /etc/apt/sources.list.d/gcsfuse.list
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg 2>/dev/null
          sed -i 's|deb |deb [signed-by=/usr/share/keyrings/cloud.google.gpg] |' /etc/apt/sources.list.d/gcsfuse.list
          apt-get update -qq && apt-get install -y -qq gcsfuse >/dev/null

          # ── Python deps ──
          pipi "numpy>=1.26"
          pipi torch --index-url https://download.pytorch.org/whl/cpu
          pipi transformers huggingface_hub safetensors tokenizers gcsfs
${extra_pip:+          $extra_pip}

          # ── Download code ──
          curl -fsSL -o /tmp/sglang-jax.tar.gz "${TARBALL_URL}"
          mkdir -p /app/sglang-jax /app
          curl -fsSL -o /app/bench.py "${BENCH_URL}"

          # ── Install sglang-jax ──
          cd /app/sglang-jax && tar xzf /tmp/sglang-jax.tar.gz && rm /tmp/sglang-jax.tar.gz
          cd /app/sglang-jax/sglang-jax/python && pipi -e ".[tpu]" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
          pip cache purge 2>/dev/null || true

          # ── Fast-fail guards (5 seconds, no TPU needed) ──
          python3 -c "from sgl_jax.srt.configs.model_config import MoEBackend; print('MoEBackend: OK')"
          python3 -c "import jax; print('TPU devices:', jax.device_count()); assert jax.device_count()>=4"

          # ── Mount weights ──
          mkdir -p \${MODEL_DIR}
          gcsfuse --implicit-dirs -o ro --only-dir \${WEIGHTS_SUBDIR} --metadata-cache-ttl-secs=-1 \${WEIGHTS_BUCKET} \${MODEL_DIR}
          [ -f "\${MODEL_DIR}/config.json" ] || { echo FATAL-noconfig; exit 2; }

          # ── Run ──
          python3 -u /app/bench.py
        env:
        - {name: WEIGHTS_BUCKET, value: "${WEIGHTS_BUCKET}"}
        - {name: WEIGHTS_SUBDIR, value: "${WEIGHTS_SUBDIR}"}
        - {name: MODEL_DIR, value: "${MODEL_DIR}"}
        - {name: TP_SIZE, value: "${TP_SIZE}"}
        - {name: MOE_BACKEND, value: "${moe_backend}"}
        - {name: TARGET_IN, value: "${TARGET_IN}"}
        - {name: TARGET_OUT, value: "${TARGET_OUT}"}
        - {name: WARMUP_ROUNDS, value: "${WARMUP_ROUNDS}"}
        - {name: TIMED_ROUNDS, value: "${TIMED_ROUNDS}"}
        - {name: JAX_COMPILATION_CACHE_DIR, value: "${compile_cache}"}
        - {name: GCS_WEIGHTS_PREFIX, value: "${GCS_WEIGHTS_PREFIX}"}
        - {name: MOE_PARALLEL_GROUPS, value: "${MOE_PARALLEL_GROUPS}"}
        - {name: SGLANG_MOE_LOAD_WORKERS, value: "${SGLANG_MOE_LOAD_WORKERS}"}
        - {name: PALLAS_COMPILER_PARAMS, value: "--disable_sparse_core_dma_merging=true"}
        - {name: TPU_MIN_LOG_LEVEL, value: "1"}
        - {name: TF_CPP_MIN_LOG_LEVEL, value: "1"}
${bs_env:+$bs_env}
        resources:
          limits: {ephemeral-storage: 40Gi, google.com/tpu: "4"}
          requests: {ephemeral-storage: 30Gi, google.com/tpu: "4"}
        securityContext: {privileged: true}
      nodeSelector:
        cloud.google.com/gke-nodepool: ${nodepool}
        cloud.google.com/gke-tpu-accelerator: tpu7x
        cloud.google.com/gke-tpu-topology: 2x2x1
      restartPolicy: Never
      tolerations:
      - {effect: NoSchedule, key: google.com/tpu, operator: Equal, value: present}
YAML
}

# ── 部署 + 监控单个 backend ──────────────────────────────────────
deploy_one() {
  local label="$1" moe_backend="$2" nodepool="$3" extra_pkgs="$4" bs_paddings="$5"
  local job_name="ling-v3-flash-longctx-bench-${label}"

  echo -e "${GREEN}=== Deploy ${label} (moe_backend=${moe_backend}) ===${NC}"
  echo "  commit: 20260625-033020-2e437ae8"

  # 清理旧 job
  kubectl delete job "$job_name" --ignore-not-found >/dev/null 2>&1

  # 生成 + 部署
  local yaml_file="/tmp/bench-${label}.yaml"
  gen_yaml "$label" "$moe_backend" "$nodepool" "$extra_pkgs" "$bs_paddings" > "$yaml_file"
  kubectl apply -f "$yaml_file"

  # 等 Pod 启动
  echo -n "  waiting for pod ... "
  for i in $(seq 1 12); do
    sleep 5
    local status; status=$(kubectl get pods -l "batch.kubernetes.io/job-name=${job_name}" -o jsonpath='{.items[0].status.phase}' 2>/dev/null || echo "")
    case "$status" in
      Running) echo "Running"; break ;;
      Error|Failed) echo "FAILED"; kubectl logs "job/${job_name}" --tail=20 2>/dev/null; return 1 ;;
    esac
  done

  # 监控直到完成
  echo "  monitoring ..."
  while true; do
    sleep 30
    local log; log=$(kubectl logs "job/${job_name}" --tail=15 2>/dev/null || echo "")

    if echo "$log" | grep -q "BENCH_RESULT"; then
      echo -e "${GREEN}  DONE${NC}"
      echo "$log" | grep "BENCH_RESULT"
      return 0
    fi

    if echo "$log" | grep -qE "Error|FATAL|Traceback|ModuleNotFoundError|ValueError"; then
      echo -e "${YELLOW}  ERROR${NC}"
      echo "$log" | tail -10
      return 1
    fi

    local progress; progress=$(echo "$log" | sed -n 's/.*Loading MoE Weights: \([0-9]*%\).*/\1/p' | tail -1)
    local ts; ts=$(echo "$log" | sed -n 's/.*\(\[20[0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]\]\).*/\1/p' | tail -1)
    echo "    $(date +%H:%M:%S) ${ts} ${progress}"
  done
}

# ── 查找 backend 定义 ──────────────────────────────────────────
find_backend() {
  local target="$1"
  for entry in "${BACKENDS[@]}"; do
    IFS='|' read -r label rest <<< "$entry"
    [ "$label" = "$target" ] && { echo "$entry"; return 0; }
  done
  return 1
}

# ── Main ──────────────────────────────────────────────────────────
main() {
  local targets=()
  if [ $# -eq 0 ]; then
    targets=(v1 v2 v4)
  else
    targets=("$@")
  fi

  # 验证 targets
  for t in "${targets[@]}"; do
    if ! find_backend "$t" &>/dev/null; then
      echo "Unknown backend: $t (valid: v1 v2 v4)" >&2
      exit 1
    fi
  done

  local results=()

  for t in "${targets[@]}"; do
    local entry; entry=$(find_backend "$t")
    IFS='|' read -r label moe_backend nodepool extra_pkgs bs_paddings <<< "$entry"

    if deploy_one "$label" "$moe_backend" "$nodepool" "$extra_pkgs" "$bs_paddings"; then
      results+=("$label: PASS")
    else
      results+=("$label: FAIL")
    fi
    echo
  done

  echo "=== Summary ==="
  for r in "${results[@]}"; do echo "  $r"; done
}

main "$@"
